version: '3'
services:
    docker-registry:
        container_name: registry
        image: registry:2
        restart: always
        environment:
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
        volumes:
            - ./data:/var/lib/registry
            - ./auth:/auth
networks:
    default:
        external:
            name: reverseproxy_reverse-proxy-bridge
